// <auto-generated />
namespace PokeMap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdminFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191757009_AdminFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
